version: '3.9'
networks:
  match-up-bot-dev:
    driver: bridge
services:
  app:
    container_name: match-up-bot
    image: match-up-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - match-up-bot-dev
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: TelegramBot
    ports:
      - "5432:5432"
    networks:
      - match-up-bot-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: