create table "__EFMigrationsHistory"
(
    "MigrationId"    varchar(150) not null
        constraint "PK___EFMigrationsHistory"
            primary key,
    "ProductVersion" varchar(32)  not null
);

alter table "__EFMigrationsHistory"
    owner to postgres;

create table "Interests"
(
    "Id"   uuid not null
        constraint "PK_Interests"
            primary key,
    "Name" text not null
);

alter table "Interests"
    owner to postgres;

create table "Users"
(
    "TgId"                bigint generated by default as identity
        constraint "PK_Users"
            primary key,
    "Name"                text    not null,
    "Age"                 integer not null,
    "City"                text    not null,
    "Gender"              text    not null,
    "TgUsername"          text    not null,
    "Stage"               integer not null,
    "About"               text    not null,
    "ZodiacSign"          text    not null,
    "IsZodiacSignMatters" boolean not null,
    "GenderOfInterest"    text    not null,
    "LastShowedBlankTgId" bigint  not null,
    "IsNotified"          boolean not null,
    "IsVip"               boolean not null
);

alter table "Users"
    owner to postgres;

create table "BlanksShowingHistory"
(
    "Id"               uuid                     not null
        constraint "PK_BlanksShowingHistory"
            primary key,
    "ReceivedUserTgId" bigint                   not null
        constraint "FK_BlanksShowingHistory_Users_ReceivedUserTgId"
            references "Users"
            on delete cascade,
    "ShownUserTgId"    bigint                   not null
        constraint "FK_BlanksShowingHistory_Users_ShownUserTgId"
            references "Users"
            on delete cascade,
    "Date"             timestamp with time zone not null
);

alter table "BlanksShowingHistory"
    owner to postgres;

create index "IX_BlanksShowingHistory_ReceivedUserTgId"
    on "BlanksShowingHistory" ("ReceivedUserTgId");

create index "IX_BlanksShowingHistory_ShownUserTgId"
    on "BlanksShowingHistory" ("ShownUserTgId");

create table "CreditCards"
(
    "Id"             uuid   not null
        constraint "PK_CreditCards"
            primary key,
    "UserId"         bigint not null
        constraint "FK_CreditCards_Users_UserId"
            references "Users"
            on delete cascade,
    "CardNumber"     text   not null,
    "HolderName"     text   not null,
    "ExpirationTime" text   not null,
    "CVV"            text   not null
);

alter table "CreditCards"
    owner to postgres;

create index "IX_CreditCards_UserId"
    on "CreditCards" ("UserId");

create table "InterestWeightEntities"
(
    "Id"                 uuid     not null
        constraint "PK_InterestWeightEntities"
            primary key,
    "UserId"             bigint   not null
        constraint "FK_InterestWeightEntities_Users_UserId"
            references "Users"
            on delete cascade,
    "SportWeight"        smallint not null,
    "ArtWeight"          smallint not null,
    "NatureWeight"       smallint not null,
    "MusicWeight"        smallint not null,
    "TravelWeight"       smallint not null,
    "PhotoWeight"        smallint not null,
    "CookingWeight"      smallint not null,
    "MovieWeight"        smallint not null,
    "LiteratureWeight"   smallint not null,
    "ScienceWeight"      smallint not null,
    "TechnologiesWeight" smallint not null,
    "HistoryWeight"      smallint not null,
    "PsychologyWeight"   smallint not null,
    "ReligionWeight"     smallint not null,
    "FashionWeight"      smallint not null
);

alter table "InterestWeightEntities"
    owner to postgres;

create unique index "IX_InterestWeightEntities_UserId"
    on "InterestWeightEntities" ("UserId");

create table "Likes"
(
    "Id"            uuid   not null
        constraint "PK_Likes"
            primary key,
    "LikedByUserId" bigint not null
        constraint "FK_Likes_Users_LikedByUserId"
            references "Users"
            on delete restrict,
    "LikedUserId"   bigint not null
        constraint "FK_Likes_Users_LikedUserId"
            references "Users"
            on delete restrict
);

alter table "Likes"
    owner to postgres;

create index "IX_Likes_LikedByUserId"
    on "Likes" ("LikedByUserId");

create index "IX_Likes_LikedUserId"
    on "Likes" ("LikedUserId");

create table "UserInterestsEntities"
(
    "Id"         uuid   not null
        constraint "PK_UserInterestsEntities"
            primary key,
    "UserId"     bigint not null
        constraint "FK_UserInterestsEntities_Users_UserId"
            references "Users"
            on delete cascade,
    "InterestId" uuid   not null
        constraint "FK_UserInterestsEntities_Interests_InterestId"
            references "Interests"
            on delete cascade
);

alter table "UserInterestsEntities"
    owner to postgres;

create index "IX_UserInterestsEntities_InterestId"
    on "UserInterestsEntities" ("InterestId");

create index "IX_UserInterestsEntities_UserId"
    on "UserInterestsEntities" ("UserId");