public enum Action
{
    SetName = 0,
    SetAge,
    SetCity,
    SetSex,
    SetAbout,
    SetIsZodiacSignMatter,
    SetInterestedSex,
    SetPhoto,
    SetMainPhoto,
    SetAdditionalPhoto ,
    SetZodiacSign = 10,
    EditCity,
    AddMainPhoto,
    AddAdditionalPhoto,
    DeleteMainPhoto,
    DeleteAdditionalPhoto,
    EditName,
    EditProfile,
    EditAge,
    EditDescription,
    EnterAction = 20,
    GetFirstBlank,
    GetBlank,
    GetLikedBlank,
    AddInterest,
    ViewMyself,
    ConfirmDeleting
}